// <auto-generated />
namespace WebApiExample.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class add_mig_bir : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "202301281654450_add_mig_bir"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEANVXy27bOhDdX6D/IHDVu6jopkDRBHKL1E4Ko9dJUaXteiyNHaJ86IpUYH9bF/2k/kKH1sOyLNtJEKDoTiRnzhwO53CoXz9+Ru+WSgZ3mFth9JC9DAcsQJ2YVOjFkBVu/uINe/f22T/RRaqWwdfa7sTbkae2Q3brXHbGuU1uUYENlUhyY83chYlRHFLDTwaDN/zlgCNBMMIKguhzoZ1QuB7QcGR0gpkrQE5NitJW87QSr1GDK1BoM0hwyL7h7DwTF0tQmcSwtA8TCdaiZcG5FECcYpTzBxIcnHqCrAlNwS+IpFvdrDJcEyBYV6SoXduIzD7iamuCpj7lJsPcrT7jfNt1MmYB33bnXf/Ge9fVcxmyiXavTlhwVUgJM0kTc5AWWZC9PoudyfEDaszBYfoJnMOczmviAWgvVU7Ostf3S8spH5z4tHDQ2jhwdPg7/PvZ+kHNN3Y5lRMLLsUS0/9QL9xtw3kKy3qGPlnwRQuqPnJyeYE9e7xX8LjI9R+NT6kqbB3+vTESQR8Bi/im3HaLkBTiQNCxVoH8GJfdSixtY3SVlS3pEJMNdimOsC7lXg5NtI0QeanEWrF8j2SjKWQZJbsl4WomiEv9jl7ED1emKjF4YnsE2rBtIpEIYIGdVZ+0FC9Fbt0YHMzAn8AoVT1mB3NbR+mkuHsFbDJeO/jv0unQHRb2XjLtTF7S5hRZrPeJDa8911PlGycgId9/s4yMLJQ+clfdA6vUfQ9aufBgvEbKPZDN2sNRK4H2gVZLu5gR7xxA98j5zpl3bvpuDR2SXtekid5IsCO1qCr74y10RwelCQsoWXci9RqIV9ahCr1BGP8vR1KsL4vaYApazNG6G/Md/XOAZPr43ts0GWtT+Vc0YOFzcbTVPq53tBunvoM8uYX8uYLlv0/UDJ8Gc6vBzYR74ubWvacPt7mml+3vcmWFD1k6M8S65Bk33fGRPXBXcBFvv2yjMVqx2ED4d67GxL+iNqC1zUTPTZ1s2lqbUW3SOYspOkgpQ+e5E3NIHC0naO36qfMVZEEmF2qG6URfFy4r3Dm1FzWTq/Z+I344/rrRb3OOrjM/sk+xBaIpaAt4rd8XQqYN78ueEtoD4YulUiGxoqcewS1WDdKV0fcEqtI3xgy1r4sbpO5MYPZax3CH+7kdz+F2xqKxgEUOqp3Bcqau5/W7YBOCArQ9NvH8jxn3f2ZvfwOZnYMlyw0AAA=="; }
        }
    }
}
